accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    # path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    #path(''leaves/pending/all/',views.leaves_list,,name='userunblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),
    


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # # Emergency
    # path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # # Family
    # path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    # #Bank
    # path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),

    path('leaves/cancel/<int:id>/',views.cansel_leave_emp,name='canselleaveapprove_emp'),
    path('leaves/uncancel/<int:id>/',views.create_leave_emp,name='createleaveapprove_emp'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview2'),

    # ###path('leave/unapprove/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),
    path('leave/unapprove2/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),



    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),


    path("dashboard/",views.you,name='you'),

]

hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'LMS ADMINISTRATION'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class UserAddForm(UserCreationForm):
	'''
	Extending UserCreationForm - with email

	'''
	email = forms.EmailField(label="メールアドレス",widget=forms.EmailInput(attrs={'placeholder':'eg.rajparmar@.com'}))
	username = forms.CharField(label='ユーザ名',widget=forms.TextInput(attrs={'placeholder':'ユーザ名'}))
	password1 = forms.CharField(label='パスワード',widget=forms.PasswordInput(attrs={'placeholder':'パスワード'}))
	password2 = forms.CharField(label='パスワード確認',widget=forms.PasswordInput(attrs={'placeholder':'パスワード確認'}))

	class Meta:
		model = User
		fields = ['username','email','password1','password2']
		

	





class UserLogin(forms.Form):
	username = forms.CharField(label='ユーザ名',widget=forms.TextInput(attrs={'placeholder':'usesrname'}))
	password = forms.CharField(label='パスワード',widget=forms.PasswordInput(attrs={'placeholder':'password'}))

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from employee.models import *
from .forms import UserLogin,UserAddForm


def changepassword(request):
	if not request.user.is_authenticated:
		return redirect('/')
	'''
	Please work on me -> success & error messages & style templates
	'''
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save(commit=True)
			update_session_auth_hash(request,user)

			messages.success(request,'Password changed successfully',extra_tags = 'alert alert-success alert-dismissible show' )
			return redirect('accounts:changepassword')
		else:
			messages.error(request,'Error,changing password',extra_tags = 'alert alert-warning alert-dismissible show' )
			return redirect('accounts:changepassword')
			
	form = PasswordChangeForm(request.user)
	return render(request,'accounts/change_password_form.html',{'form':form})




def register_user_view(request):
	# WORK ON (MESSAGES AND UI) & extend with email field
	if request.method == 'POST':
		form = UserAddForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			instance.save()
			username = form.cleaned_data.get("username")

			messages.success(request,'Account created for {0} !!!'.format(username),extra_tags = 'alert alert-success alert-dismissible show' )
			return redirect('accounts:register')
		else:
			messages.error(request,'Username or password is invalid',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('accounts:register')


	form = UserAddForm()
	dataset = dict()
	dataset['form'] = form
	dataset['title'] = 'register users'
	return render(request,'accounts/register.html',dataset)




def login_view(request):
	'''
	work on me - needs messages and redirects
	
	'''
	login_user = request.user
	if request.method == 'POST':
		form = UserLogin(data = request.POST)
		if form.is_valid():
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username = username, password = password)
			if user and user.is_active:
				login(request,user)
				if login_user.is_authenticated:
					return redirect('dashboard:dashboard')
			else:
			    messages.error(request,'Account is invalid',extra_tags = 'alert alert-error alert-dismissible show' )
			    return redirect('accounts:login')

		else:
			return HttpResponse('data not valid')

	dataset=dict()
	form = UserLogin()

	dataset['form'] = form
	return render(request,'accounts/login.html',dataset)



"""
def user_profile_view(request):
 	'''
 	user profile view -> staffs (No edit) only admin/HR can edit.
 	'''
 	user = request.user
 	if user.is_authenticated:
 		employee = Employee.objects.filter(user = user).first()
		

 		dataset = dict()
 		dataset['employee'] = employee
	
		

 		return render(request,'dashboard/employee_detail.html',dataset)
 	return HttpResponse("Sorry , not authenticated for this,admin or whoever you are :)")

"""



def logout_view(request):
	logout(request)
	return redirect('accounts:login')



def users_list(request):
	employees = Leave.objects.all()
	# employees = UserAddForm.username.all()
	employees = User.objects.all()
	kanrisya = str(request.user)
	return render(request,'accounts/users_table.html',{'employees':employees,'title':'Users List','kanrisya':kanrisya})


def users_unblock(request,id):
	user = get_object_or_404(User,id = id)
	# emp = Employee.objects.filter(user = user).first()
	emp = User.objects.filter(username = emp).first()
	emp.delete()
	emp.is_blocked = False
	emp.save()
	user.is_active = True
	user.save()

	return redirect('accounts:users')


def users_block(request,id):
	user = get_object_or_404(User,id = id)
	#emp = User.objects.filter(username = user)
	emp =  User.objects.filter(username = user)
	emp.delete()
	#emp = emp.first.delete()
	user.is_blocked = True
	#emp.is_deleted = True
	#emp.save()
	
	user.is_active = False
	
	#user.save()
	
	return redirect('accounts:users')



def users_blocked_list(request):
	blocked_employees = Employee.objects.all_blocked_employees()
	return render(request,'accounts/all_deleted_users.html',{'employees':blocked_employees,'title':'blocked users list'})

templates/accounts/all_deleted_users.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}


 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}
        <!--CONTENTS-->
 {% block content %}
        <section class="content">

            <section class="container-fluid">
            		<section class="row">
            			<section class="col col-lg-12 text-center">
            				<h3 class="title-h3">List of Deleted Users</h3>
            			</section>
            		</section>
                	<!-- TABLE -->
                		<table class="table table-striped">
							  <thead>
							    <tr>
							      <th scope="col"><b>Username</b></th>
							      <th scope="col"><b>Employee</b></th>
							      <th scope="col"><b>Department</b></th>
							      <td scope="col"><b>Action</b></td>
							    </tr>
							  </thead>

							  <tbody>
							  	{% for emp in employees %}
							  	<tr>
								      <td>{{emp.user.username}}</td>
								      <td>{{ emp.get_full_name }}</td>
								      <td>{{ emp.department }}</td>
								      <td>Unblock</td>
							    </tr>
							   {% endfor %}
							  </tbody>
						</table>
                	

            </section> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

templates/accounts/change_password_form.html
{% load static %}

{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Login </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="{% static 'css/forms_styles.css' %}" rel="stylesheet" />

</head>

<style type="text/css">
    
html,body{
    overflow: hidden;
    height: 100%;
}

.shadow{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
}

.wrapper-form-index-page{
    padding: 4%;
}


/* ------ center form -------*/
.parent-wrap{
    display: table;
    width: 100%;
    height: 100%;
}

.sub-parent-wrap{
    display:table-cell;
    vertical-align:middle;
    padding:15px;
}

/* ----- center form ---------*/

.btn-custom{
    padding: 4px 16px !important;
    background: transparent !important;
    color: #505050 !important;
    border: 2px solid #8282e6 !important;
    transition: all 400ms ease;
}

.btn-custom:hover{
   color: #565656 !important; 
}

.forgt-pass-wrp{
    margin-top: 5px;
}

.forgt-pass-wrp a {
    text-decoration: none;
}

label {
    font-weight: 100;
    font-size: 16px;
}


h3{
    font-weight: 100 !important;
    font-size: 25px;
}



 #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

}

.alert-warning{
    background:#fd7b7b;
}

.alert-success {
    background-color: #82b72a;
}

.alert-success,.alert-warning{
    font-size:16px;
}


</style>

<body>
<section class="parent-wrap">


  <section class="sub-parent-wrap">

    <section class="container">
      <section class="row">
        <section class="col col-sm-12">
                  {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                      {% endfor %}
                  {% endif %}
        </section>
      </section>
          <section class="row">

             <div class="col-lg-6 col-lg-offset-3">
                <div class="wrapper-form-index-page shadow">
                    <div class="row text-center">
                        <h3 class="title-h3">Password Change Form</h3>
                    </div>

                     <form action="" method="POST" id="login_form">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button  type="submit" class="btn btn-primary btn-lg btn-block btn-custom">Change Password</button>
                     </form>

                     <section class="container" style="margin-top: 1rem;">
                       <div class="row">
                         <p> Go to <a href="{% url 'dashboard:dashboard' %}" style="color:#ae6cff;">dashboard</a></p>
                       </div>
                     </section>

                </div>
             </div>
        
          </section>
    </section><!-- container-->
  </section>
</section>

</body>
    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>


<script type="text/javascript">
    $(document).ready(function(){
      

    });

</script>


</html>

templates/accounts/login.html
{% load static %}

{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> LMS - Login </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="{% static 'css/forms_styles.css' %}" rel="stylesheet" />


	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Alice" rel="stylesheet">

</head>

<style type="text/css">
    
html,body{
    overflow: hidden;
    height: 100%;
}


.shadow{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
}

.wrapper-form-index-page{
    padding: 4%;
}


/* ------ center form -------*/
.parent-wrap{
    display: table;
    width: 100%;
    height: 100%;
    /*background-color: #f7f7f7;*/
}

.sub-parent-wrap{
    display:table-cell;
    vertical-align:middle;
    padding:15px;
}

/* ----- center form ---------*/

.btn-custom{
    padding: 4px 16px !important;
    background: #4caf50;
    color: #f0f0f0 !important;
    transition: all 400ms ease;
}

.btn-custom:hover{
   color: #565656 !important; 
}

.forgt-pass-wrp{
    margin-top: 5px;
}

.forgt-pass-wrp a {
    text-decoration: none;
}

label {
    font-weight: 100;
    font-size: 16px;
}


h3{
    font-weight: 100 !important;
    font-size: 25px;
}

.navbar{
    margin-bottom: 0 !important;
}

  a{
    font-variant: petite-caps;
    font-weight: 100;
    font-size: 16px;
  }

#override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

}

.alert-error{
    background:#fd7b7b;
    text-align: center;
    font-size: 17px;
}

.alert-success,.alert-warning{
    font-size:16px;
}

  
        a{
                font-variant: petite-caps;
                font-weight: 100;
                font-size: 16px;
        }


        .navbar-brand{
          font-variant: petite-caps;
          font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
          font-weight: 600;
          font-size: 3.1rem;
          color: #e4a530;
         

        }


        h2{
          font-family: 'Alice', serif;
          color: gold;
          font-size: 4.9rem;


        }
      body{
          position: relative;
          /*background: #243177;*/

        }

        
        a{
                font-variant: petite-caps;
                font-weight: 100;
                font-size: 16px;
        }


        .navbar-brand{
          font-variant: petite-caps;
          font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
          font-weight: 600;
          font-size: 3.1rem;
          color: #e4a530;
       

        }


        h2{
          font-family: 'Alice', serif;
          color: gold;
          font-size: 4.9rem;


        }



        p{
          font-variant: small-caps;
          color: #cecece;

        }

        p span{
          color: #a5a5a5;
          font-weight: bold;
        }

        span.icon{
          font-size: 15px;
        }

        .content{
          position: relative;
          height: 100vh;
        }

        .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px !important;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }


        .back-link{
          color: #fff;
          font-size: 2.6rem;
          font-weight: 900;
          transition: all 400ms ease-in-out;
        }

        .back-link:hover{
          color: #fff;
          font-size: 2.8rem;
          transition: all 400ms ease-in-out;
        }

        .container-centered-items{
          position: absolute;
          top: 50%;
          left: 0;
          right: 0;
        }


</style>

<body>
        <!-- Navigation -->
                <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>

                          <a class="navbar-brand" href="/">LMS <span class="sub-title">Django</span></a>
                          
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                       
                      </div><!-- /.container-fluid -->
                </nav>
            <!-- /Naivagtion -->
<section class="parent-wrap">

  <section class="sub-parent-wrap">

    <section class="container">
         <section class="row">
            <section class="col col-sm-12">
                  {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                      {% endfor %}
                  {% endif %}
            </section>
         </section>

          <section class="row">

             <div class="col-lg-6 col-lg-offset-3">
                <div class="wrapper-form-index-page shadow">
                    <div class="row text-center">
                        <h3 class="title-h3">ログイン画面</h3>
                    </div>

                     <form action="" method="POST" id="login_form">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button  type="submit" class="btn btn-primary btn-lg btn-block btn-custom">ログイン</button>
                        <div class="forgt-pass-wrp">
                            <!-- <a href="">Forgotten your password ?</a> -->
                        </div>
                     </form>

                </div>
             </div>
        
          </section>
    </section><!-- container-->
  </section>
</section>

</body>
    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

</html>

templates/accounts/register.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_tags %}

 {% block navheader %}
    {% include 'includes/navheader_employee_app.html' %}
 {% endblock %}

 {% block stylesheet %}
    .form-wrapper{
        -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
        box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
        padding: 2%;
        background:#fff !important;
        padding-bottom:5%;
    }




 #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

}

.alert-warning{
    background:#fd7b7b;
}

.alert-success {
    background-color: #82b72a;
}

.alert-success,.alert-warning{
    font-size:16px;
}

 {% endblock %}

 {% block content %}
        <section class="content">
            <section class="container-fluid">
           
                <section class="form-wrapper">
                    <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12 text-center">
                            <h3 class="title-h3">Add User</h3>
                            <p>ユーザの新規登録ができます．</p>
                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {{form | crispy }}
                                <button type="submit" class="btn btn-primary btn-lg btn-block">登録</button>
                            </form>
                        </section>

                    </section>

                </section>

            </section> <!-- /container --> 
        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}
/*create-user-button - handler*/

// $(document).ready(function(){

// var createuser = $('.create-user-model');
// createuser.on('click',function(){
// alert("who clicked me ?")

// });


// });

{% endblock %}
</script>

templates/accounts/user_profile_page.html
<img src="{{ emp.image.url}}"/>

{{user.username}}<br>
{{user.email}}<br>
{{emp.department}}<br>
{{emp.role}}

templates/accounts/users_table.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}
{% load crispy_forms_tags %}
 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}

 {% block stylesheet %}

	.pe-7s-lock,.pe-7s-unlock{
		font-size: 16px;
	    font-weight: 600;
	}

	.pe-7s-unlock{
		color:#22c322;
	}

	.pe-7s-lock{
		color:#dc233c;
	}
	.pe-7s-close{
		font-size: 20px;
	    font-weight: 600;
	}
	.pe-7s-close{
		color:red;
	}

	.table-shadow{
		
		background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}

	h4{
	margin:2px 0 5px 0 !important;
			
	
	}
	.table{
		color:black;
		
		font-size: 18px;
	    font-weight: bold;
	}

	.table-description{

		<!-- GOOGLE FONTS-STYLE -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}

{% endblock %}
        <!--CONTENTS-->
 }
 {% block content %}
        <section class="content">

            <section class="container-fluid">
            	<!-- <section class="row">
            		<section class="col col-lg-12 text-centered">
            			
            		</section>
            	</section> -->
                	<!-- TABLE -->
                	<div class="table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3">板橋ユーザ</h4>
                		</div>
                		<div class="container-fluid">
                			<div class="row">
                			 	<div class="download-print-action">
                			  		Download Excel | Pdf | Print
                				</div>
                			</div>
                		</div>
                		<table class="table">
							  <thead>
							    <tr>
							      <th scope="col">ユーザ名</th>
							      
							      <th scope="col">削除</th>
							    </tr>
							  </thead>
							  
							  <tbody>
								{% for emp in employees %}
							  	<tr>
								      <td>{{ emp.username }}</td>
									  

									  {% if kanrisya == emp.username %}
									  <td>管理者</td>
									  {% else %}
									  <td><a href="{% url 'accounts:userblock' emp.id %}" title="block user"><i class="pe-7s-close"></i></a></td>  
									  {% endif %}

									  
								     
								    
								      
								   
							  </tr>
							   {% endfor %}
							  </tbody>
						</table>
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}
/*create-user-button - handler*/

// $(document).ready(function(){

// var createuser = $('.create-user-model');
// createuser.on('click',function(){
// alert("who clicked me ?")

// });


// });

{% endblock %}
</script>