accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    # path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    #path(''leaves/pending/all/',views.leaves_list,,name='userunblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),
    


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # # Emergency
    # path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # # Family
    # path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    # #Bank
    # path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),

    path('leaves/cancel/<int:id>/',views.cansel_leave_emp,name='canselleaveapprove_emp'),
    path('leaves/uncancel/<int:id>/',views.create_leave_emp,name='createleaveapprove_emp'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview2'),

    # ###path('leave/unapprove/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),
    path('leave/unapprove2/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),



    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),


    path("dashboard/",views.you,name='you'),

]

hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'LMS ADMINISTRATION'

employee/models.py
import datetime
from employee.utility import code_format
from django.db import models
from employee.managers import EmployeeManager
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from leave.models import Leave




# Create your models here.
class Role(models.Model):

    name = models.CharField(max_length=125)
    description = models.CharField(max_length=125,null=True,blank=True)

    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)


    class Meta:
        verbose_name = _('Role')
        verbose_name_plural = _('Roles')
        ordering = ['name','created']


    def __str__(self):
        return self.name


class Department(models.Model):


    name = models.CharField(max_length=125)
    description = models.CharField(max_length=125,null=True,blank=True)

    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)


    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')
        ordering = ['name','created']
    
    def __str__(self):
        return self.name



class Employee(models.Model):

    MALE = 'male'
    FEMALE = 'female'
    OTHER = 'other'
    NOT_KNOWN = 'Not Known'

    GENDER = (
    (MALE,'Male'),
    (FEMALE,'Female'),
    (OTHER,'Other'),
    (NOT_KNOWN,'Not Known'),
    )

    MR = 'Mr'
    MRS = 'Mrs'
    MSS = 'Mss'
    DR = 'Dr'
    SIR = 'Sir'
    MADAM = 'Madam'

    TITLE = (
    (MR,'Mr'),
    (MRS,'Mrs'),
    (MSS,'Mss'),
    (DR,'Dr'),
    (SIR,'Sir'),
    (MADAM,'Madam'),
    )


    FULL_TIME = 'Full-Time'
    PART_TIME = 'Part-Time'
    CONTRACT = 'Contract'
    INTERN = 'Intern'

    EMPLOYEETYPE = (
    (FULL_TIME,'Full-Time'),
    (PART_TIME,'Part-Time'),
    (CONTRACT,'Contract'),
    (INTERN,'Intern'),
    )


    
    
    # PERSONAL DATA
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    
    image = models.FileField(_('Profile Image'),upload_to='profiles',default='default.png',blank=True,null=True,help_text='upload image size less than 2.0MB')#work on path username-date/image
    firstname = models.CharField(_('Firstname'),max_length=125,null=False,blank=False)
    lastname = models.CharField(_('Lastname'),max_length=125,null=False,blank=False)
    othername = models.CharField(_('Othername (optional)'),max_length=125,null=True,blank=True)
    birthday = models.DateField(_('Birthday'),blank=False,null=False)
   
 
    department =  models.ForeignKey(Department,verbose_name =_('Department'),on_delete=models.SET_NULL,null=True,default=None)
    role =  models.ForeignKey(Role,verbose_name =_('Role'),on_delete=models.SET_NULL,null=True,default=None)
    startdate = models.DateField(_('Employement Date'),help_text='date of employement',blank=False,null=True)
    employeetype = models.CharField(_('Employee Type'),max_length=15,default=FULL_TIME,choices=EMPLOYEETYPE,blank=False,null=True)
    employeeid = models.CharField(_('Employee ID Number'),max_length=10,null=True,blank=True)
    dateissued = models.DateField(_('Date Issued'),help_text='date staff id was issued',blank=False,null=True)

    # app related
    is_blocked = models.BooleanField(_('Is Blocked'),help_text='button to toggle employee block and unblock',default=False)
    is_deleted = models.BooleanField(_('Is Deleted'),help_text='button to toggle employee deleted and undelete',default=False)
 
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True,null=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True,null=True)


    #PLUG MANAGERS
    objects = EmployeeManager()

    
    
    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        ordering = ['-created']



    def __str__(self):
        return self.get_full_name

    

    @property
    def get_full_name(self):
        fullname = ''
        firstname = self.firstname
        lastname = self.lastname
        othername = self.othername

        if (firstname and lastname) or othername is None:
            fullname = firstname +' '+ lastname
            return fullname
        elif othername:
            fullname = firstname + ' '+ lastname +' '+othername
            return fullname
        return


    @property
    def get_age(self):
        current_year = datetime.date.today().year
        dateofbirth_year = self.birthday.year
        if dateofbirth_year:
            return current_year - dateofbirth_year
        return



    @property
    def can_apply_leave(self):
        pass





   

    





    def save(self,*args,**kwargs):
        '''
        overriding the save method - for every instance that calls the save method 
        perform this action on its employee_id
        added : March, 03 2019 - 11:08 PM

        '''
        get_id = self.employeeid #grab employee_id number from submitted form field
        data = code_format(get_id)
        self.employeeid = data #pass the new code to the employee_id as its orifinal or actual code
        super().save(*args,**kwargs) # call the parent save method
        # print(self.employeeid)

leave/models.py
from django.db import models
from .manager import LeaveManager
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime


# Create your models here.
SICK = '年休'
CASUAL = 'AM年休'
EMERGENCY = 'PM年休'
STUDY = '研修'
MATERNITY = 'その他'
#BEREAVEMENT = 'bereavement'
#QUARANTINE = 'quarantine'
#COMPENSATORY = 'compensatory'
#SABBATICAL = 'sabbatical'

LEAVE_TYPE = (
(SICK,'年休'),
(CASUAL,'AM年休'),
(EMERGENCY,'PM年休'),
(STUDY,'研修'),
(MATERNITY, 'その他'),
#(BEREAVEMENT, 'Bereavement Leave'),
#(QUARANTINE, 'Self Quarantine'),
#(COMPENSATORY, 'Compensatory Leave'),
#(SABBATICAL, 'Sabbatical Leave')
)

DAYS = 30



class Leave(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
	startdate = models.DateField(verbose_name=_('開始日'),help_text='leave start date is on ..',null=True,blank=False)
	enddate = models.DateField(verbose_name=_('終了日'),help_text='coming back on ...',null=True,blank=False)
	leavetype = models.CharField(verbose_name=_('理由'),choices=LEAVE_TYPE,max_length=25,default=SICK,null=True,blank=False)
	reason = models.CharField(verbose_name=_('Reason for Leave'),max_length=255,help_text='add additional information for leave',null=True,blank=True)
	defaultdays = models.PositiveIntegerField(verbose_name=_('Leave days per year counter'),default=DAYS,null=True,blank=True)

	

	status = models.CharField(max_length=12,default='申請中') #pending,approved,rejected,cancelled
	is_approved = models.BooleanField(default=False) #hide

	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	created = models.DateTimeField(auto_now=False, auto_now_add=True)


	objects = LeaveManager()


	class Meta:
		verbose_name = _('Leave')
		verbose_name_plural = _('Leaves')
		ordering = ['-created'] #recent objects



	def __str__(self):
		return ('{0} - {1}'.format(self.leavetype,self.user))




	@property
	def pretty_leave(self):
		'''
		i don't like the __str__ of leave object - this is a pretty one :-)
		'''
		leave = self.leavetype
		user = self.user
		employee = user.employee_set.first().get_full_name
		return ('{0} - {1}'.format(employee,leave))



	@property
	def leave_days(self):
		days_count = ''
		startdate = self.startdate
		enddate = self.enddate
		if startdate > enddate:
			return
		dates = (enddate - startdate)
		ddd = dates.days
		ddd = ddd + 1
		return ddd



	@property
	def leave_approved(self):
		return self.is_approved == True




	@property
	def approve_leave(self):
		if not self.is_approved:
			self.is_approved = True
			self.status = '承認済'
			self.save()




	@property
	def unapprove_leave(self):
		if self.is_approved:
			self.is_approved = False
			self.status = '申請中'
			self.save()

	@property
	def unapprove_leave2(self):
		if self.is_approved:
			self.is_approved = False
			self.status = '申請中'
			self.save()



	@property
	def leaves_cancel(self):
		if self.is_approved or not self.is_approved:
			self.is_approved = False
			self.status = 'キャンセル'
			self.save()






	@property
	def reject_leave(self):
		if self.is_approved or not self.is_approved:
			self.is_approved = False
			self.status = '却下'
			self.save()



	@property
	def is_rejected(self):
		return self.status == '却下'

templates/_layout.html
{% load static %}

{% load humanize %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Dashboard - LMS | {% block title %} {{ title }} {% endblock %}</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="author" content="Mike Edward <Fullstack Developer/>,mail - edward.mike.anaryo@gmail.com">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script type="text/javascript"><!--
        function sublist( target ) {
           var TargetList = target.parentNode.getElementsByTagName('ul');
           if ( TargetList[0].style.display == 'none' ) {
              TargetList[0].style.display = 'block';
           }
           else {
              TargetList[0].style.display = 'none';
           }
        }
        allshowhide('none');
        // --></script>

        

</head>
<body>


    <style type="text/css">

        .title-h3{
        font-weight: bold;
        font-variant: petite-caps;
    }


     .sidebar{
    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2); 
     transition: all 400ms ease-in;
    }
    
    .sidebar:hover{
        -webkit-box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    box-shadow: 0 8px 17px 2px rgba(0,0,0,0.14), 0 3px 14px 2px rgba(0,0,0,0.12), 0 5px 5px -3px rgba(0,0,0,0.2);
    }


    .shadow{
        box-shadow:0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
     }

     a.simple-text{
        font-family: 'Russo One', sans-serif;
     }

      a.simple-text > span{
        font-size: 13px !important;
      }

      .logo a{
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
      }

    .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    }


    tr td{
        font-variant: petite-caps;
    }

    {% block stylesheet %}
     
     
    {% endblock %}
    </style>

<div class="wrapper">
    <div class="sidebar" data-color="red" data-image="{% static 'img/sidebar-46.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    勤務表申請システム
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <i class="pe-7s-graph"></i>
                        <p>ダッシュボード</p>
                    </a>
                </li>
                <!-- <li class="">
                    <a href="/">
                        <i class="pe-7s-home"></i>
                        <p>Home</p>
                    </a>
                </li> -->
                
                {% if request.user.is_superuser and request.user.is_staff %}
                <li>
                    <a href="{% url 'dashboard:employees' %}">
                        <i class="pe-7s-users"></i>
                        <p>従業員</p>
                    </a>
                </li>
                {% endif %}
                
                {% if request.user.is_superuser %}
                <ul style="list-style-type: none">

                     <!-- 折り畳み展開ポインタ1 -->
                    <div onclick="obj=document.getElementById('open1').style; obj.display=(obj.display=='none')?'block':'none';">
                    <li><a style="cursor:pointer;"> 申請 ▼</a></li>
                    </div>
                    <!--// 折り畳み展開ポインタ1 -->
                    
                        <!-- 折り畳まれ部分1 -->
                        <div id="open1" style="display:none;clear:both;">
                        <ul style="list-style-type: none">
                    
                            
                            <li><a href="{% url 'dashboard:leaveslist' %}">申請リスト</a></li>
                            <li><a href="{% url 'dashboard:approvedleaveslist' %}">承認済リスト</a></li>
                            <li><a href="{% url 'dashboard:canceleaveslist' %}">キャンセルリスト</a></li>
                            <li><a href="{% url 'dashboard:leavesrejected' %}">却下リスト</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'dashboard:createleave' %}">申請する</a></li>
            
                    
                        
                        </ul>
                    
                        </div>
                        <!--// 折り畳まれ部分1 -->
                    
                    </li>
                    </ul>
                    {% endif %}
                <li>
                    {% if request.user.is_superuser %}<a href="{% url 'dashboard:leaveslist' %}">{% else %}<a href="{% url 'dashboard:staffleavetable' %}"> {% endif %}
                        <i class="pe-7s-news-paper"></i>
                        <p>申請リスト</p>
                    </a>
                </li>
                <li>
                    {% if request.user.is_superuser %}<a href="{% url 'dashboard:createleave' %}">{% else %}<a href="{% url 'dashboard:createleave' %}"> {% endif %}
                        <i class="pe-7s-news-paper"></i>
                        <p>申請する</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:you' %}">
                        <i class="pe-7s-news-paper"></i>
                        <p>申請る</p>
                    </a>
                </li>

                
            </ul>
    	</div>


    </div>

    <div class="main-panel">
    <!--EVERY APP DEFINES ITS ROUTES  -->
    {% block navheader %}
        {% include 'includes/navheader_default.html' %}
    {% endblock %}
    <!-- NAVHEADER -->       

        
    <!--CONTENTS-->
    {% block content %}
    <section class="content">
        <section class="container-fluid">
                


        </section> <!-- /container -->           
     </section>
    {% endblock %}
    <!--/CONTENTS-->

        
        
    </div>
</div>


</body>



    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'js/demo.js' %}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script type="text/javascript">
        {% block extrajs%}

 

        {% endblock %}
    </script>

<script type="text/javascript">


    function previewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('.prev-holder .prev-avatar').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    
    $(document).ready(function(){

        $('.refresh-page').click(function(){
            /*Script refreshes the page*/
            console.log('refresh page clicked !!!');
            location.reload(true);

        });


        $( "#id_birthday,#id_dateissued,#id_startdate,#id_enddate" ).datepicker({
            dateFormat: 'yy-mm-dd'
        });


    });
    
	</script>

</html>

templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Leave Management Django </title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <!-- Bootstrap core CSS     -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alice" rel="stylesheet">
  



</head>
<body>

    <style type="text/css">
        body{
          position: relative;
          background: #5a4747;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, #d04247, #5a4747);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, #d04247, #5a4747); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

        }

        
        a{
                font-variant: petite-caps;
                font-weight: 100;
                font-size: 16px;
        }


        .navbar-brand{
          font-variant: petite-caps;
          font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
          font-weight: 600;
          font-size: 3.1rem;
          color: #e4a530;
          

        }


        h2{
          font-family: 'Alice', serif;
          color: gold;
          font-size: 4.9rem;


        }



        p{
          font-variant: small-caps;
          color: #cecece;

        }

        p span{
          color: #a5a5a5;
          font-weight: bold;
        }

        span.icon{
          font-size: 15px;
        }

        .content{
          position: relative;
          height: 100vh;
        }

        .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px !important;
        font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }

        .back-link{
          color: #fff;
          font-size: 2.6rem;
          font-weight: 900;
          transition: all 400ms ease-in-out;
        }

        .back-link:hover{
          color: #fff;
          font-size: 2.8rem;
          transition: all 400ms ease-in-out;
        }

        .container-centered-items{
          position: absolute;
          top: 50%;
          left: 0;
          right: 0;
        }

    </style>

    <!--CONTENTS-->
 
    <section class="content">
            <!-- Navigation -->
                <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                          {% if request.user.is_authenticated %}
                          <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">LMS<span class="sub-title"></span></a>
                          {% else %}
                          <a class="navbar-brand" href="/">Leave Management</a>
                          {% endif %}
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          
                          <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
                          </ul>
                        </div><!-- /.navbar-collapse -->
                      </div><!-- /.container-fluid -->
                </nav>
            <!-- /Naivagtion -->

            <div class="container-fluid container-centered-items">
                <section class="row">
                  <section class="">
                     <section class="col col-lg-12 text-center">
                        <div class="center-me-please">
                            <h2>勤務表申請システム</h2>
                            <p></p>
                            <p>Click to <a class='' href="{% url 'accounts:login' %}" style="text-decoration: none;color: #ffffff;"><b>ログイン</b></a>
                            </p>
                        </div>
                     </section>
                  </section>
              </section>
            </div>
     </section> <!-- /content -->
    <div>
       {% if request.user.is_authenticated %}
                    <p style="position: absolute;bottom: 0;"><a href="{{request.META.HTTP_REFERER|escape}}" class="back-link" title="back to previous page"><i class="pe-7s-back-2"></i></a></p>
       {% endif %}
    </div>

</body>

    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
  


	<script type="text/javascript">
  
  
	</script>
 

</html>