dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # # Emergency
    # path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    # path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # # Family
    # path('family/create/',views.dashboard_family_create,name='familycreate'),
    # path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    # #Bank
    # path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    # path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),

    path('leaves/cancel/<int:id>/',views.cansel_leave_emp,name='canselleaveapprove_emp'),
    path('leaves/uncancel/<int:id>/',views.create_leave_emp,name='createleaveapprove_emp'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview2'),

    # ###path('leave/unapprove/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),
    path('leave/unapprove2/<int:id>/',views.unapprove_leave2,name='userleaveunapprove2'),



    # BIRTHDAY ROUTE
    # path('birthdays/all/',views.birthday_this_month,name='birthdays'),


    path("dashboard/",views.you,name='you'),

]

hrsuit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views


urlpatterns = [
    path('admin/', admin.site.urls),#change url in production --> rabotecsuits.com/_&_wysiwyg-suits_empty-link_url
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'LMS ADMINISTRATION'

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from employee.forms import EmployeeCreateForm
from leave.models import Leave
from employee.models import *
from leave.forms import LeaveCreationForm


def dashboard(request):
	
	'''
	Summary of all apps - display here with charts etc.
	eg.lEAVE - pending|APPROVED|RECENT|REJECTED - TOTAL THIS MONTH or NEXT MONTH
	EMPLOYEE - TOTAL | GENDER 
	CHART - AVERAGE EMPLOYEE AGES
	'''
	dataset = dict()
	user = request.user

	if not request.user.is_authenticated:
		return redirect('accounts:login')

	employees = Employee.objects.all()
	leaves = Leave.objects.all_pending_leaves()
	# leaves = Employee.objects.all()
	staff_leaves = Leave.objects.filter(user = user)

	
	dataset['employees'] = employees
	dataset['leaves'] = leaves
	
	dataset['staff_leaves'] = staff_leaves
	dataset['title'] = 'summary'
	

	return render(request,'dashboard/dashboard_index.html',dataset)




def dashboard_employees(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	dataset = dict()
	departments = Department.objects.all()
	employees = Employee.objects.all()

	#pagination
	query = request.GET.get('search')
	if query:
		employees = employees.filter(
			Q(firstname__icontains = query) |
			Q(lastname__icontains = query)
		)



	paginator = Paginator(employees, 10) #show 10 employee lists per page

	page = request.GET.get('page')
	employees_paginated = paginator.get_page(page)



	blocked_employees = Employee.objects.all_blocked_employees()


	return render(request,'dashboard/employee_app.html',dataset)




def dashboard_employees_create(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.title = request.POST.get('title')
			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			
			instance.birthday = request.POST.get('birthday')

			

			



			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			

			instance.save()

			

			return  redirect('dashboard:employees')
		else:
			messages.error(request,'Trying to create dublicate employees with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('dashboard:employeecreate')


	dataset = dict()
	form = EmployeeCreateForm()
	dataset['form'] = form
	dataset['title'] = 'register employee'
	return render(request,'dashboard/employee_create.html',dataset)


def employee_edit_data(request,id):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	employee = get_object_or_404(Employee, id = id)
	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
		if form.is_valid():
			instance = form.save(commit = False)

			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			
			instance.birthday = request.POST.get('birthday')

			religion_id = request.POST.get('religion')
			religion = Religion.objects.get(id = religion_id)
			instance.religion = religion

			nationality_id = request.POST.get('nationality')
			nationality = Nationality.objects.get(id = nationality_id)
			instance.nationality = nationality

			department_id = request.POST.get('department')
			department = Department.objects.get(id = department_id)
			instance.department = department


			instance.hometown = request.POST.get('hometown')
			instance.region = request.POST.get('region')
			instance.residence = request.POST.get('residence')
			instance.address = request.POST.get('address')
			instance.education = request.POST.get('education')
			instance.lastwork = request.POST.get('lastwork')
			instance.position = request.POST.get('position')
			instance.ssnitnumber = request.POST.get('ssnitnumber')
			instance.tinnumber = request.POST.get('tinnumber')

			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			# now = datetime.datetime.now()
			# instance.created = now
			# instance.updated = now

			instance.save()
			messages.success(request,'Account Updated Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:employees')

		else:

			messages.error(request,'Error Updating account',extra_tags = 'alert alert-warning alert-dismissible show')
			return HttpResponse("Form data not valid")

	dataset = dict()
	form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
	dataset['form'] = form
	dataset['title'] = 'edit - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_create.html',dataset)






def dashboard_employee_info(request,id):
	if not request.user.is_authenticated:
		return redirect('/')
	
	employee = get_object_or_404(Employee, id = id)
	
	
	dataset = dict()
	dataset['employee'] = employee
	dataset['title'] = 'profile - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_detail.html',dataset)






# ---------------------LEAVE-------------------------------------------



def leave_creation(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')
	if request.method == 'POST':
		form = LeaveCreationForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.user
			instance.user = user
			instance.save()


			# print(instance.defaultdays)
			messages.success(request,'申請が完了しました',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:createleave')

		messages.error(request,'申請できません．日付を確認してください',extra_tags = 'alert alert-warning alert-dismissible show')
		return redirect('dashboard:createleave')


	dataset = dict()
	form = LeaveCreationForm()
	dataset['form'] = form
	dataset['title'] = '申請画面'
	
	return render(request,'dashboard/create_leave.html',dataset)
	







def leaves_list(request):
	if not (request.user.is_staff and request.user.is_superuser):
		return redirect('/')
	leaves = Leave.objects.all_pending_leaves()
	return render(request,'dashboard/leaves_recent.html',{'leave_list':leaves,'title':'leaves list - pending'})



def leaves_approved_list(request):
	if not (request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	leaves = Leave.objects.all_approved_leaves() #approved leaves -> calling model manager method
	return render(request,'dashboard/leaves_approved.html',{'leave_list':leaves,'title':'approved leave list'})



def leaves_view(request,id):
	if not (request.user.is_authenticated):
		return redirect('/')

	leave = get_object_or_404(Leave, id = id)

	print(leave.user)
	employee = Employee.objects.filter(user = leave.user).first()
	return render(request,'dashboard/leave_detail_view.html',{'leave':leave,'employee':employee,'title':'{0}-{1} leave'.format(leave.user.username,leave.status)})





def approve_leave(request,id):
	# if not (request.user.is_authenticated):
	if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	user = leave.user
	employee = Employee.objects.filter(user = user)
	leave.approve_leave

	messages.error(request,' {0}さんの予定を承認しました'.format(user),extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:userleaveview', id = id)

###################################################
# 追加＿承認
def cansel_leave_emp(request,id):
	if not (request.user.is_authenticated):
	# if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	user = leave.user
	employee = Employee.objects.filter(user = user)
	# leave.approve_leave
	leave.leaves_cancel
	leave.is_canceled = True
	leave.save()
	messages.error(request,'キャンセルされました'.format(user),extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:userleaveview', id = id)


def create_leave_emp(request,id):
	if not (request.user.is_authenticated):
	# if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	user = leave.user
	employee = Employee.objects.filter(user = user)
	leave = get_object_or_404(Leave, id = id)
	leave.status = '申請中'
	leave.a = True
	leave.save()

templates/dashboard/leave_detail_view.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_tags %}

 {% block navheader %}
    {% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



  {% block stylesheet %}
    .rounded-circle-image{
    border-radius: 50% !important;
    width:250px;
    height:250px;
  }

  .form-wrapper{
  background:#fff;
  -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);

  padding-top: 2rem;
  padding-bottom: 2rem;

}


.list-group {
  margin-top: 10px;
}

span{
  color: #6f6f6f;
  font-weight: lighter;
  font-size: 16px;
}


.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid transparent;
    font-size:17px;
}

  #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

    }

    .alert-warning{
        background:#fd7b7b;
    }

    .alert-success {
      background-color: #82b72a;    
    }

    .alert-success,.alert-warning{
        font-size:16px;
    }

    .employee-name-title{
    color: #3873b1;
    font-weight: 600;
    font-variant: petite-caps;
    font-size: 3.1rem !important;
  }

  span,.list-group-item > div{
  font-variant: petite-caps;
}




.panel-default>.panel-heading {
  color: #fff !important;
  background-color: #2d88a9 !important;
}

.panel-title a:hover{
color:#e6e4e4;
}

.panel-title a:active{
color:#e6e4e4;
}

.panel-title a:focus{
color:#e6e4e4;
}

  {% endblock %}


  
  <html lang="ja">
 {% block content %}
        <section class="content">
            <section class="container-fluid">
           
                <section class="form-wrapper">
                    <section class="row">
                        <section class="col col-lg-8 col-md-12  col-sm-12">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                            <h3 class="title-h3">{{ employee.get_full_name }}</h3>
                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-4 text-center">
                          <img src="{{ employee.image.url}}"  class="img-fluid rounded-circle-image">
                        </section>
                        <section class="col-lg-8 col-md-12 col-sm-12">
                                    <div class="list-group" id="list-tab" role="tablist">
                                            <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>氏名</span> <div><b>{{ leave.user }}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>開始日</span> <div> <b>{{ leave.startdate.year }}-{{ leave.startdate.month }}-{{ leave.startdate.day }}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>終了日</span><div> <b>{{ leave.enddate.year }}-{{ leave.enddate.month }}-{{ leave.enddate.day }}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>期間</span> <div><b>{{ leave.leave_days}}日</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>理由</span> <div><b>{{ leave.leavetype}}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>備考</span> <div><b>{{ leave.reason}}</b></div>
                                            </a>
                                             <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>状態</span> <div><b>{{ leave.status}}</b></div>
                                             </a>

                                       
                                      </div>

                        </section>
                    </section>


                             
                                  <span style="font-size: 13px;padding-left: 1rem;" class="pull-left">作成日 <b>{{ leave.created }}</b></span>
                              

              {% if request.user.is_superuser and request.user.is_staff %}

                    <section class="row">
                      <section class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
                        <div class="btn-group btn-group-justified">
                          {%if leave.leave_approved %}
                          <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-danger" style="background-color:blue; color: white;" name='unapprove'>申請中
                          </a>
                          {% else %}
                          <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-success" style="background-color:green; color: white;" name='approve'>承認
                          </a>
                          {% endif %}
                          <!--<a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info" style="background-color:rgb(0, 142, 185); color: white;" name='cancel'>キャンセル</a>-->
                          <a href="{% url 'dashboard:reject' leave.id %}" class="btn btn-danger" style="background-color:rgb(185, 0, 0); color: white;" name='reject'>却下</a>  
                          <a href="{% url 'dashboard:leaveslist' %}" class="btn btn-danger" style="background-color:rgb(104, 77, 77);border: none; color: white;" name='reject'>申請リスト</a> 
                          
                        </div>
                      </section>
                    </section>
              {% else %}
              
              <section class="row">
                <section class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
                  <div class="btn-group btn-group-justified">
                    {%if leave.status == '申請中' %}
                    <a href="{% url 'dashboard:canselleaveapprove_emp' leave.id %}" class="btn btn-danger" style="background-color:rgb(189, 138, 0);border: none; color: white;" name='cancel'>キャンセル
                    </a>
                    <a href="{% url 'dashboard:staffleavetable' %}" class="btn btn-success" style="background-color:rgb(104, 77, 77);border: none; color: white;" name='approve'>申請リストへ
                    </a>
                    {% elif leave.status == 'キャンセル' %}
                    <a href="{% url 'dashboard:createleaveapprove_emp' leave.id %}" class="btn btn-success" style="background-color:blue;border: none; color: white;" name='cancel'>再申請
                    </a>
                    <a href="{% url 'dashboard:staffleavetable' %}" class="btn btn-success" style="background-color:rgb(104, 77, 77);border: none; color: white;" name='approve'>申請リストへ
                    </a>
                    {% else %}
                    <!--<a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info" style="background-color:rgb(0, 142, 185); color: white;" name='cancel'>キャンセル</a>-->
                    <a href="{% url 'dashboard:staffleavetable' %}" class="btn btn-success" style="background-color:rgb(104, 77, 77); border: none; color: white;" name='approve'>申請リストへ
                    </a>
                    {% endif %}
                  </div>
                </section>
              </section>        
              {% endif %}

                </section>

            </section> <!-- /container --> 
        </section>
 {% endblock %}
 </html>
<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>

templates/dashboard/staff_leaves_table.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}

 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 width:200px;
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}

body {
	font-size:17px;
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #d04247 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#d04247;
}





{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="text-shadow: 1px 0px rgba(0,0,0,0.11)">申請リスト</h4>
                		</div>
                		{% if leave_list %}
						
                		<table class="table">
							  <thead>
							    <tr>
							      <!-- <th scope="col">#</th> -->
							      <th scope="col"><b>種類</b></th>
							      <th scope="col"><b>日数</b></th>
							      <th scope="col"><b>状態</b></th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for leave in leave_list %}
							    <tr>

							      <td>{{ leave.leavetype}}</td>
							      <td>{{ leave.leave_days  }}</td>
							      {% if leave.status == '申請中' %}
							      <td ><span class="badge badge-success" style="background-color:blue; font-size: 14px;">{{ leave.status }}</span></td>
								  {% elif leave.status == '却下' %}
							      <td ><span class="badge badge-success" style="background-color:rgb(184, 12, 0); font-size: 14px;">{{ leave.status }}</span></td> 
								  
								  {% elif leave.status == '承認済' %}
							      <td ><span class="badge badge-success" style="background-color:green; font-size: 14px;">{{ leave.status }}</span></td> 
								  {% else %}
								  
							      <td ><span class="badge badge-warning" style="background-color:rgb(189, 138, 0); font-size: 14px;">{{ leave.status }}</span></td>
							      {% endif %}

							      <td> 
							      	<a href="{% url 'dashboard:userleaveview' leave.id %}" style="color: #795548;">
							      	    詳細
							      	</a>
									<a>
									　　
								    </a>
									<a>
									{% if leave.status == '申請中' %}
									<span><a href= "{% url 'dashboard:canselleaveapprove_emp' leave.id %}" style="color: black;" name='cancel'>キャンセル			
									</span></a>
									{% elif leave.status == 'キャンセル' %}
									<span><a href= "{% url 'dashboard:createleaveapprove_emp' leave.id %}" style="color: black;" name='cancel'>再申請			
									</span></a>
									
									{% endif %}

									
									
					
									
							      </td>
							    </tr>

							    {% endfor %}

							  </tbody>

						</table>
						{% else %}

						<span>No Leaves can be found...</span>
						{% endif %}
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>